CREATE OR ALTER PROCEDURE VuelosComerciales (@FECHASALIDA DATE)
AS
BEGIN
	DECLARE @FECHAUNI SMALLDATETIME
	DECLARE @PORCENTAJE INT
	SET @FECHAUNI = CONVERT (DATE, @FECHASALIDA)

	SELECT COUNT(*) FROM Vuelo V
		INNER JOIN Avion A ON A.idAvion=V.idAvion
		WHERE CONVERT(DATE ,V.FechaSalida)=@FECHAUNI AND A.idTipoAvion=1 
		AND ((CONVERT(FLOAT,(SELECT COUNT(*) FROM VueloPasajero WHERE idTipoEstatus=2 or idTipoEstatus=3 and V.idVuelo=idVuelo))/(SELECT SUM(Cantidad) FROM Asiento WHERE A.idAvion=idAvion))*100)>85
	RETURN;
END
GO

EXEC VuelosComerciales '2021/11/08 8AM'
