CREATE TABLE TipoAvion(
	idTipoAvion INT IDENTITY(1,1),
	Tipo VARCHAR(20) NOT NULL,

	CONSTRAINT PK_TIPOAVION PRIMARY KEY(idTipoAvion)
)

CREATE TABLE Avion(
	idAvion INT IDENTITY(1,1),
	idTipoAvion INT,
	Compañia VARCHAR(50) NOT NULL,
	Carga DECIMAL (10,2) NOT NULL,
	Alcance INT NOT NULL,

	CONSTRAINT PK_AVION PRIMARY KEY(idAvion),
	CONSTRAINT FK_AVION_TIPOAVION FOREIGN KEY(idTipoAvion) REFERENCES TipoAvion(idTipoAvion)
)

CREATE TABLE TipoAsiento(
	idTipoAsiento INT IDENTITY(1,1),
	Tipo VARCHAR(20) NOT NULL,

	CONSTRAINT PK_TIPOASIENTO PRIMARY KEY(idTipoAsiento)
)

CREATE TABLE Asiento(
	idAsiento INT IDENTITY(1,1),
	idAvion INT,
	idTipoAsiento INT,
	Cantidad SMALLINT NOT NULL,

	CONSTRAINT PK_ASIENTO PRIMARY KEY(idAsiento),
	CONSTRAINT FK_AVION FOREIGN KEY(idAvion) REFERENCES Avion(idAvion),
	CONSTRAINT FK_TIPOASIENTO FOREIGN KEY(idTipoAsiento) REFERENCES TipoAsiento(idTipoAsiento)
)

CREATE TABLE TipoPasajero(
	idTipoPasajero INT IDENTITY(1,1),
	Tipo VARCHAR(20) NOT NULL,

	CONSTRAINT PK_TIPOPASAJERO PRIMARY KEY(idTipoPasajero)
)

CREATE TABLE Pasajero(
	idPasajero INT IDENTITY(1,1),
	idTipoPasajero INT,
	Nombres VARCHAR(100) NOT NULL,
	Apellidos VARCHAR(100) NOT NULL,
	Pasaporte VARCHAR(9) NOT NULL,
	FechaNacimiento DATE NOT NULL,

	CONSTRAINT PK_PASAJERO PRIMARY KEY(idPasajero),
	CONSTRAINT FK_PASAJERO_TIPOPASAJERO FOREIGN KEY(idTipoPasajero) REFERENCES TipoPasajero(idTipoPasajero)
)

CREATE TABLE Vuelo(
	idVuelo INT IDENTITY(1,1),
	idAvion INT,
	Estatus BIT NOT NULL DEFAULT 1,
	CiudadOrigen VARCHAR(20) NOT NULL,
	CiudadDestino VARCHAR(20) NOT NULL,
	AeropuertoOrigen VARCHAR(3) NOT NULL,
	AeropuertoDestino VARCHAR(3) NOT NULL,
	FechaSalida SMALLDATETIME NOT NULL,
	FechaLlegada SMALLDATETIME NOT NULL,
	Jornada VARCHAR(1) NOT NULL,

	CONSTRAINT PK_VUELO PRIMARY KEY(idVuelo),
	CONSTRAINT FK_VUELO_AVION FOREIGN KEY(idAvion) REFERENCES Avion(idAvion)
)

CREATE TABLE Escala(
	idEscala INT IDENTITY(1,1),
	idVuelo INT,
	Destino VARCHAR(20) NOT NULL,
	FechaHora SMALLDATETIME NOT NULL,
	
	CONSTRAINT PK_ESCALA PRIMARY KEY(idEscala),
	CONSTRAINT FK_ESCALA_VUELO FOREIGN KEY(idVuelo) REFERENCES Vuelo(idVuelo)
)

CREATE TABLE TipoEstatus(
	idTipoEstatus INT IDENTITY(1,1),
	Estatus VARCHAR(20) NOT NULL,

	CONSTRAINT PK_TIPOESTATUS PRIMARY KEY(idTipoEstatus)
)

CREATE TABLE VueloPasajero(
	idVueloPasajero INT IDENTITY(1,1),
	idVuelo INT,
	idPasajero INT DEFAULT NULL,
	idAsiento INT DEFAULT NULL,
	NoAsiento INT NOT NULL,
	idTipoEstatus INT NOT NULL DEFAULT 1,
	Fecha SMALLDATETIME DEFAULT NULL,

	CONSTRAINT PK_VUELOPASAJERO PRIMARY KEY(idVueloPasajero),
	CONSTRAINT FK_VUELOPASAJERO_VUELO FOREIGN KEY(idVuelo) REFERENCES Vuelo(idVuelo),
	CONSTRAINT FK_VUELOPASAJERO_PASAJERO FOREIGN KEY(idPasajero) REFERENCES Pasajero(idPasajero),
	CONSTRAINT FK_VUELOPASAJERO_ASIENTO FOREIGN KEY(idAsiento) REFERENCES Asiento(idAsiento),
	CONSTRAINT FK_VUELOPASAJERO_ESTATUS FOREIGN KEY(idTipoEstatus) REFERENCES TipoEstatus(idTipoEstatus)
)

CREATE TABLE Cola(
	idCola INT IDENTITY(1,1),
	idPasajero INT,
	idVueloPasajero INT,
	Fecha SMALLDATETIME,

	CONSTRAINT PK_COLA PRIMARY KEY (idCola),
	constraint FK_COLA_PASAJERO FOREIGN KEY(idPasajero) REFERENCES Pasajero(idPasajero),
	CONSTRAINT FK_COLA_VUELOPASAJERO FOREIGN KEY(idVueloPasajero) REFERENCES VueloPasajero(idVueloPasajero)
)