
---OPTIMIZACION DE CONSULTAS
----SE LEEE DE IZQUIERDA A DERECHA
SELECT*
FROM SYS.objects
WHERE TYPE = 'U'
AND NAME LIKE '%sales%'
--1810105489 = SALESORDERDETAIL

SELECT*
FROM SYS.stats
WHERE object_id = 1810105489

DBCC SHOW_STATISTICS('Sales.SalesOrderDetail','PK_SalesOrderDetail_SalesOrderID_SalesOrderDetailID')


SELECT*
FROM SALES.SalesOrderDetail
WHERE UnitPrice > 1000

CREATE TABLE TABLAPLAN(
	ID INT IDENTITY(1,1),
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(50),
	DIRECCION VARCHAR(50)

);

INSERT INTO TABLAPLAN VALUES('ABCDFEG','BARRIOS','RUIZ')
GO 1000
INSERT INTO TABLAPLAN VALUES('ABCDFE','BARR','RAIZ')
GO 1000
DROP TABLE TABLAPLAN

SELECT* FROM TABLAPLAN
SELECT NOMBRE,COUNT(1) FROM TABLAPLAN
GROUP BY NOMBRE
