//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProyectoBDDEntities : DbContext
    {
        public ProyectoBDDEntities()
            : base("name=ProyectoBDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiento> Asiento { get; set; }
        public virtual DbSet<Avion> Avion { get; set; }
        public virtual DbSet<Cola> Cola { get; set; }
        public virtual DbSet<Escala> Escala { get; set; }
        public virtual DbSet<Pasajero> Pasajero { get; set; }
        public virtual DbSet<TipoAsiento> TipoAsiento { get; set; }
        public virtual DbSet<TipoAvion> TipoAvion { get; set; }
        public virtual DbSet<TipoEstatus> TipoEstatus { get; set; }
        public virtual DbSet<TipoPasajero> TipoPasajero { get; set; }
        public virtual DbSet<Vuelo> Vuelo { get; set; }
        public virtual DbSet<VueloPasajero> VueloPasajero { get; set; }
        public virtual DbSet<TranLog> TranLog { get; set; }
    
        public virtual int SP_INGRESAR_VUELO(Nullable<int> aVION, string cIUDADO, string cIUDADD, string aEROPUERTOO, string aEROPUERTOD, Nullable<System.DateTime> fECHAS, Nullable<System.DateTime> fECHAL)
        {
            var aVIONParameter = aVION.HasValue ?
                new ObjectParameter("AVION", aVION) :
                new ObjectParameter("AVION", typeof(int));
    
            var cIUDADOParameter = cIUDADO != null ?
                new ObjectParameter("CIUDADO", cIUDADO) :
                new ObjectParameter("CIUDADO", typeof(string));
    
            var cIUDADDParameter = cIUDADD != null ?
                new ObjectParameter("CIUDADD", cIUDADD) :
                new ObjectParameter("CIUDADD", typeof(string));
    
            var aEROPUERTOOParameter = aEROPUERTOO != null ?
                new ObjectParameter("AEROPUERTOO", aEROPUERTOO) :
                new ObjectParameter("AEROPUERTOO", typeof(string));
    
            var aEROPUERTODParameter = aEROPUERTOD != null ?
                new ObjectParameter("AEROPUERTOD", aEROPUERTOD) :
                new ObjectParameter("AEROPUERTOD", typeof(string));
    
            var fECHASParameter = fECHAS.HasValue ?
                new ObjectParameter("FECHAS", fECHAS) :
                new ObjectParameter("FECHAS", typeof(System.DateTime));
    
            var fECHALParameter = fECHAL.HasValue ?
                new ObjectParameter("FECHAL", fECHAL) :
                new ObjectParameter("FECHAL", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INGRESAR_VUELO", aVIONParameter, cIUDADOParameter, cIUDADDParameter, aEROPUERTOOParameter, aEROPUERTODParameter, fECHASParameter, fECHALParameter);
        }
    
        public virtual int SP_CONFIRMAR_ASIENTO(Nullable<int> idPasajero, Nullable<int> idVuelo, Nullable<int> noAsiento)
        {
            var idPasajeroParameter = idPasajero.HasValue ?
                new ObjectParameter("idPasajero", idPasajero) :
                new ObjectParameter("idPasajero", typeof(int));
    
            var idVueloParameter = idVuelo.HasValue ?
                new ObjectParameter("idVuelo", idVuelo) :
                new ObjectParameter("idVuelo", typeof(int));
    
            var noAsientoParameter = noAsiento.HasValue ?
                new ObjectParameter("NoAsiento", noAsiento) :
                new ObjectParameter("NoAsiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CONFIRMAR_ASIENTO", idPasajeroParameter, idVueloParameter, noAsientoParameter);
        }
    
        public virtual int SP_INGRESAR_CLIENTE(Nullable<int> idTipoPasajero, string nombres, string apellidos, string pasaporte, Nullable<System.DateTime> fechaNacimiento)
        {
            var idTipoPasajeroParameter = idTipoPasajero.HasValue ?
                new ObjectParameter("idTipoPasajero", idTipoPasajero) :
                new ObjectParameter("idTipoPasajero", typeof(int));
    
            var nombresParameter = nombres != null ?
                new ObjectParameter("Nombres", nombres) :
                new ObjectParameter("Nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("Apellidos", apellidos) :
                new ObjectParameter("Apellidos", typeof(string));
    
            var pasaporteParameter = pasaporte != null ?
                new ObjectParameter("Pasaporte", pasaporte) :
                new ObjectParameter("Pasaporte", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INGRESAR_CLIENTE", idTipoPasajeroParameter, nombresParameter, apellidosParameter, pasaporteParameter, fechaNacimientoParameter);
        }
    
        public virtual int SP_INGRESAR_CLIENTE_BULK(string path)
        {
            var pathParameter = path != null ?
                new ObjectParameter("path", path) :
                new ObjectParameter("path", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INGRESAR_CLIENTE_BULK", pathParameter);
        }
    
        public virtual int SP_INGRESAR_TRIPULACION(Nullable<int> pASAJERO, Nullable<int> vUELO)
        {
            var pASAJEROParameter = pASAJERO.HasValue ?
                new ObjectParameter("PASAJERO", pASAJERO) :
                new ObjectParameter("PASAJERO", typeof(int));
    
            var vUELOParameter = vUELO.HasValue ?
                new ObjectParameter("VUELO", vUELO) :
                new ObjectParameter("VUELO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INGRESAR_TRIPULACION", pASAJEROParameter, vUELOParameter);
        }
    
        public virtual int SP_RESERVAR_ASIENTO(Nullable<int> idVuelo, Nullable<int> noAsiento, Nullable<int> idPasajero)
        {
            var idVueloParameter = idVuelo.HasValue ?
                new ObjectParameter("idVuelo", idVuelo) :
                new ObjectParameter("idVuelo", typeof(int));
    
            var noAsientoParameter = noAsiento.HasValue ?
                new ObjectParameter("NoAsiento", noAsiento) :
                new ObjectParameter("NoAsiento", typeof(int));
    
            var idPasajeroParameter = idPasajero.HasValue ?
                new ObjectParameter("idPasajero", idPasajero) :
                new ObjectParameter("idPasajero", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RESERVAR_ASIENTO", idVueloParameter, noAsientoParameter, idPasajeroParameter);
        }
    
        public virtual int SP_INGRESAR_ESCALA(Nullable<int> vUELO, string dESTINO, Nullable<System.DateTime> fECHA)
        {
            var vUELOParameter = vUELO.HasValue ?
                new ObjectParameter("VUELO", vUELO) :
                new ObjectParameter("VUELO", typeof(int));
    
            var dESTINOParameter = dESTINO != null ?
                new ObjectParameter("DESTINO", dESTINO) :
                new ObjectParameter("DESTINO", typeof(string));
    
            var fECHAParameter = fECHA.HasValue ?
                new ObjectParameter("FECHA", fECHA) :
                new ObjectParameter("FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INGRESAR_ESCALA", vUELOParameter, dESTINOParameter, fECHAParameter);
        }
    
        public virtual int SP_CANCELAR_RESERVA(Nullable<int> vUELOPASAJERO)
        {
            var vUELOPASAJEROParameter = vUELOPASAJERO.HasValue ?
                new ObjectParameter("VUELOPASAJERO", vUELOPASAJERO) :
                new ObjectParameter("VUELOPASAJERO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CANCELAR_RESERVA", vUELOPASAJEROParameter);
        }
    
        public virtual int SP_CANCELAR_VUELO(Nullable<int> vUELO)
        {
            var vUELOParameter = vUELO.HasValue ?
                new ObjectParameter("VUELO", vUELO) :
                new ObjectParameter("VUELO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CANCELAR_VUELO", vUELOParameter);
        }
    
        public virtual ObjectResult<SP_VUELO_ASIENTOS_Result> SP_VUELO_ASIENTOS(Nullable<int> vUELO)
        {
            var vUELOParameter = vUELO.HasValue ?
                new ObjectParameter("VUELO", vUELO) :
                new ObjectParameter("VUELO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VUELO_ASIENTOS_Result>("SP_VUELO_ASIENTOS", vUELOParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_COLA_AÑO(string año, string mes)
        {
            var añoParameter = año != null ?
                new ObjectParameter("año", año) :
                new ObjectParameter("año", typeof(string));
    
            var mesParameter = mes != null ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_COLA_AÑO", añoParameter, mesParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_CONFIRMADOS_DIA(Nullable<System.DateTime> fecha)
        {
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_CONFIRMADOS_DIA", fechaParameter);
        }
    
        public virtual ObjectResult<SP_VUELO_ESCALAS_Result> SP_VUELO_ESCALAS(Nullable<int> vUELO)
        {
            var vUELOParameter = vUELO.HasValue ?
                new ObjectParameter("VUELO", vUELO) :
                new ObjectParameter("VUELO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VUELO_ESCALAS_Result>("SP_VUELO_ESCALAS", vUELOParameter);
        }
    
        public virtual int SP_INGRESAR_TRANLOG(string tX, string tIPO, string tABLA)
        {
            var tXParameter = tX != null ?
                new ObjectParameter("TX", tX) :
                new ObjectParameter("TX", typeof(string));
    
            var tIPOParameter = tIPO != null ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(string));
    
            var tABLAParameter = tABLA != null ?
                new ObjectParameter("TABLA", tABLA) :
                new ObjectParameter("TABLA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INGRESAR_TRANLOG", tXParameter, tIPOParameter, tABLAParameter);
        }
    
        public virtual ObjectResult<SP_LOGS_FECHA_Result> SP_LOGS_FECHA(Nullable<System.DateTime> fECHAINICIO, Nullable<System.DateTime> fECHAFIN)
        {
            var fECHAINICIOParameter = fECHAINICIO.HasValue ?
                new ObjectParameter("FECHAINICIO", fECHAINICIO) :
                new ObjectParameter("FECHAINICIO", typeof(System.DateTime));
    
            var fECHAFINParameter = fECHAFIN.HasValue ?
                new ObjectParameter("FECHAFIN", fECHAFIN) :
                new ObjectParameter("FECHAFIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOGS_FECHA_Result>("SP_LOGS_FECHA", fECHAINICIOParameter, fECHAFINParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_VUELOS_COMERCIALES(Nullable<System.DateTime> fECHASALIDA)
        {
            var fECHASALIDAParameter = fECHASALIDA.HasValue ?
                new ObjectParameter("FECHASALIDA", fECHASALIDA) :
                new ObjectParameter("FECHASALIDA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_VUELOS_COMERCIALES", fECHASALIDAParameter);
        }
    }
}
