//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asiento()
        {
            this.VueloPasajero = new HashSet<VueloPasajero>();
        }
    
        public int idAsiento { get; set; }
        public Nullable<int> idAvion { get; set; }
        public Nullable<int> idTipoAsiento { get; set; }
        public short Cantidad { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual TipoAsiento TipoAsiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VueloPasajero> VueloPasajero { get; set; }
    }
}
