//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cola
    {
        public int idCola { get; set; }
        public Nullable<int> idPasajero { get; set; }
        public Nullable<int> idVueloPasajero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Pasajero Pasajero { get; set; }
        public virtual VueloPasajero VueloPasajero { get; set; }
    }
}
