//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Escala
    {
        public int idEscala { get; set; }
        public Nullable<int> idVuelo { get; set; }
        public string Destino { get; set; }
        public System.DateTime FechaHora { get; set; }
    
        public virtual Vuelo Vuelo { get; set; }
    }
}
