//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranLog
    {
        public int idTranLog { get; set; }
        public string TX { get; set; }
        public string Tipo { get; set; }
        public string Tabla { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
