//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoBDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VueloPasajero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VueloPasajero()
        {
            this.Cola = new HashSet<Cola>();
        }
    
        public int idVueloPasajero { get; set; }
        public Nullable<int> idVuelo { get; set; }
        public Nullable<int> idPasajero { get; set; }
        public Nullable<int> idAsiento { get; set; }
        public Nullable<int> NoAsiento { get; set; }
        public int idTipoEstatus { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cola> Cola { get; set; }
        public virtual Pasajero Pasajero { get; set; }
        public virtual TipoEstatus TipoEstatus { get; set; }
        public virtual Vuelo Vuelo { get; set; }
    }
}
